### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of null

### ISSUE THREAD

**Issue by nh-mdev** [Adri-Glez/filepond-plugin-pdf-preview#2] opened 2021-03-24 13:10 UTC
**Describe the bug**
Using vue-filepond with the pdf preview plugin, **sometimes** the stacktraced error occurs on route change.

**To Reproduce**
1) Uploading an image
2) Waiting for it to succeed 
3) Navigating away from the current route
4) Going back to upload view
5) Remove current image
6) Upload new image
7) Navigate away from current route

**Expected behavior**
No console TypeError.

**Stacktraces**

```js
Uncaught TypeError: Cannot read property 'file' of null
    at filepond-plugin-pdf-preview.js:181
    at filepond.js:1445
    at filepond.js:1096
    at Array.forEach (<anonymous>)
    at Object._write (filepond.js:1095)
    at filepond.js:1125
    at Array.forEach (<anonymous>)
    at Object._write (filepond.js:1123)
    at filepond.js:1125
    at Array.forEach (<anonymous>)
```

**Information about your project:**
Windows 10
Google Chrome - Version 89.0.4389.90 (64-Bit)
```js
"filepond": "^4.21.1"
"filepond-plugin-file-encode": "^2.1.9"
"filepond-plugin-image-preview": "^4.6.4"
"filepond-plugin-file-validate-type": "^1.2.6"
"filepond-plugin-image-transform": "^3.7.6"
"filepond-plugin-pdf-preview": "^1.0.2"
"filepond-plugin-file-validate-size": "^2.2.4"
"vue-filepond": "^6.0.3"
```

**Additional context**
I tried "resolving/catching" this error in the beforeDestroy() life-cycle hook of the component holding vue-filepond, but the this.$refs is already undefined at that point.

**Comment by Adri-Glez** [comment] 2021-03-24 21:33
I can't reproduce it. Maybe is something in your Vue Project. 

It happens when you upload a image or a pdf? Looks like is something that do Vue on the variable context when the route change. 

Sure If we put a null check in the error line 181 Will be another null error elsewhere. The thing is know why It execute the method when the route change, maybe It shouldn't at this point, and why is null because there are a file on it, isn't it?

Anyway I can’t reproduce it, I think is something that should be fixed in your project environment, If you find a reason and a robust fix for it we can change the library.

**Closed** 2021-05-11 00:28 UTC

**Comment by Delta-Band** [comment] 2021-08-16 15:03
@Adri-Glez 
Happens to me when I upload a PDF
Using React

**Comment by simonmaass** [comment] 2021-08-16 18:51
can confirm this issue using vue

**Comment by symbianm** [comment] 2021-10-20 07:28
It happens to me too in React. Hard to reproduce, but the issue exists. See attached error log.

<img width="1137" alt="Screenshot 2021-10-20 at 10 20 04" src="https://user-images.githubusercontent.com/3383599/138047186-e23eed84-54f4-4c8e-8951-5ccb6c1169d7.png">
<img width="428" alt="Screenshot 2021-10-20 at 10 28 01" src="https://user-images.githubusercontent.com/3383599/138047320-b5a2c47d-2a75-4097-939f-ece40c604091.png">

**Comment by alkanna** [comment] 2021-12-12 21:27
Same here on svelte.

**Comment by leeovery** [comment] 2022-02-23 15:36
Same here on Vue + nuxt

**Comment by simonmaass** [comment] 2022-03-10 17:24
@Adri-Glez looks like quite a few people have this issue - maybe reopen this?

**Comment by AO-IO** [comment] 2022-08-10 15:12
same issue vue + nuxt 😕

**Comment by AO-IO** [comment] 2022-08-10 15:32
issue still there ... when changing the route the error is triggered ... vue 2 (Nuxt) 😕

![image](https://user-images.githubusercontent.com/33369979/183944361-454e1337-799e-4378-9f25-0d485f98b574.png)
